language: csharp

dotnet: 1.0.1

matrix:
   include:
      - os: linux
        dist: trusty
        sudo: required

before_install: 
   - "$TRAVIS_OS_NAME"
   - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
   - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
   - sudo apt-get update


install:
   - sudo apt-get install dotnet-dev-1.0.1

script: dotnet build

branches:
   only:
      - travis-ci